### ISSUE TITLE
Site layout kida breaks when doing certain things

### ISSUE THREAD

**Issue by Kobun42** [WillFlame14/jspuyo#56]
Hey! Just here to report a bug I found. It's more annoying than anything, to be honest.

If you press any of the "tabs" on the top then close it, the site layout will remain in an "open tab" state, and if you do that multiple times, the site layout will start to extend more.

I have video footage here if you don't understand what I mean (Excuse the watermark. No other screen recorder has worked properly, so I've just had to make do with this one.)

[https://drive.google.com/file/d/1mHVz4Uif3H9JxqZqSRdHOzvzf0t4oFLU/view?usp=sharing](url)

**Comment by WillFlame14** [comment]
Hey, thanks for reporting! I've never had that bug happen to me before, but I'll take a look at it soon. Would you be able to tell me what browser you're using?

**Comment by Kobun42** [comment]
I'm using Firefox, though I don't know if it happens on Chromium, MS Edge, or Opera. Not sure if it happens on other browsers. If I get the time to do it, I might test it on other browsers I have to see if it occurs there.

**Comment by WillFlame14** [comment]
That's odd, I tested on Firefox 81 (as well as Chrome 86) and I wasn't able to replicate the issue. It might have something to do with your monitor resolution then; are you using a resolution larger than 1920x1080?

**Comment by Kobun42** [comment]
I'm on exactly 1920x1080. I can't go higher than that.

**Comment by WillFlame14** [comment]
Yeah that's probably not related then. What version of Firefox are you using? Also testing on other browsers would be a great help to see if it's just a Firefox thing or something related to your setup. I still haven't been able to replicate anything like it on my end.

**Comment by Kobun42** [comment]
I've been using firefox 72 and now I just realized how out of date I've been. I'll continue trying to see how other browsers react, and I'll update firefox afterwards to see if it was just my version if the other browsers are not replicating such a problem

UPDATE: Does not happen on Opera.
UPDATE 2: Updated to Firefox 81. works perfectly now.

**Comment by WillFlame14** [comment]
That's awesome! I'm still not sure what the cause was, but glad it was fixed.
